/* This file is generated by scripts/generate-format-catalog.mjs. Do not edit directly. */
import type { RendererDefinition } from '../contracts/types';

export const DEFAULT_RENDERER_DEFINITIONS = [
  {
    "id": "office-word-openxml",
    "label": "Word OpenXML",
    "category": "office",
    "extensions": [
      "docx",
      "docm",
      "dotx",
      "dotm"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-word",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "OOXML Transitional",
      "OOXML Strict"
    ],
    "knownLimits": [
      "VBA is never executed"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "office-word-binary",
    "label": "Word Binary",
    "category": "office",
    "extensions": [
      "doc",
      "dot"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-word",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "Word 97-2003 Binary"
    ],
    "knownLimits": [
      "Macros are never executed"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "office-presentation-binary",
    "label": "PowerPoint 97–2003",
    "category": "office",
    "extensions": [
      "ppt",
      "pot"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-ppt",
    "presets": [
      "office",
      "all"
    ],
    "containerVersions": [
      "PowerPoint 97-2003 Binary"
    ],
    "knownLimits": [
      "Embedded engine watermark is retained",
      "Macros are never executed"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": false
    }
  },
  {
    "id": "office-presentation",
    "label": "PowerPoint OpenXML",
    "category": "office",
    "extensions": [
      "pptx",
      "pptm",
      "potx",
      "potm",
      "ppsx",
      "ppsm"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-pptx",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "OOXML Transitional",
      "OOXML Strict"
    ],
    "knownLimits": [
      "Macros and external programs are never executed"
    ],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "open-document",
    "label": "Open Document",
    "category": "office",
    "extensions": [
      "rtf",
      "odt",
      "odp"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-word",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "RTF",
      "OpenDocument"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "spreadsheet-openxml",
    "label": "Spreadsheet",
    "category": "office",
    "extensions": [
      "xlsx",
      "xltx",
      "xlsm",
      "xlsb",
      "xls",
      "xlt",
      "xla",
      "xlam",
      "xltm",
      "csv",
      "tsv",
      "ods",
      "fods"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-spreadsheet",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "OOXML",
      "BIFF",
      "OpenDocument",
      "Delimited text"
    ],
    "knownLimits": [
      "VBA and add-in code are never executed",
      "Formula results are read from the saved workbook cache"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "apple-pages",
    "label": "Apple Pages",
    "category": "office",
    "extensions": [
      "pages"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-iwork",
    "presets": [
      "office",
      "all"
    ],
    "containerVersions": [
      "iWork '09 index.xml(.gz)",
      "iWork 2013+ IWA"
    ],
    "knownLimits": [
      "Static preview only",
      "Encrypted iwpv2 files are detected but not decrypted"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "apple-numbers",
    "label": "Apple Numbers",
    "category": "office",
    "extensions": [
      "numbers"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-iwork",
    "presets": [
      "office",
      "all"
    ],
    "containerVersions": [
      "iWork '09 index.xml",
      "iWork 2013+ IWA"
    ],
    "knownLimits": [
      "Formula results are read from the saved document cache",
      "Encrypted iwpv2 files are detected but not decrypted"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "apple-keynote",
    "label": "Apple Keynote",
    "category": "office",
    "extensions": [
      "key"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-iwork",
    "presets": [
      "office",
      "all"
    ],
    "containerVersions": [
      "iWork '09 index.apxl",
      "iWork 2013+ IWA"
    ],
    "knownLimits": [
      "Animations, transitions and video playback are not executed",
      "Encrypted iwpv2 files are detected but not decrypted"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "office-wordperfect",
    "label": "WordPerfect",
    "category": "office",
    "extensions": [
      "wpd",
      "wp",
      "wp5",
      "wp6"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-wordperfect",
    "presets": [
      "office",
      "all"
    ],
    "containerVersions": [
      "WordPerfect 4.2",
      "WordPerfect 5.x",
      "WordPerfect 6+"
    ],
    "knownLimits": [
      "Macros are never executed",
      ".wp5 and .wp6 are routing aliases for genuine WP5/WP6 payloads, not separate container formats",
      "Pagination and unsupported embedded objects are presented as structured static preview"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "spreadsheet-dbf",
    "label": "dBASE Table",
    "category": "office",
    "extensions": [
      "dbf"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-spreadsheet",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "dBASE III/IV",
      "Visual FoxPro"
    ],
    "knownLimits": [
      "Missing DBT/FPT memo sidecars are reported as incomplete"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "pdf",
    "label": "PDF",
    "category": "document",
    "extensions": [
      "pdf"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-pdf",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "PDF"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": "provider"
    }
  },
  {
    "id": "ofd",
    "label": "OFD",
    "category": "document",
    "extensions": [
      "ofd"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-ofd",
    "presets": [
      "standard",
      "office",
      "all"
    ],
    "containerVersions": [
      "OFD"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "office-hangul",
    "label": "Hancom Hangul",
    "category": "office",
    "extensions": [
      "hwp",
      "hwpx"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-hangul",
    "presets": [
      "office",
      "all"
    ],
    "containerVersions": [
      "HWP v5 CFB",
      "HWPX ZIP/XML"
    ],
    "knownLimits": [
      "Encrypted, DRM-protected and distribution documents are detected but not decrypted",
      "Charts, OLE objects and advanced drawing effects remain limited in the static structured preview",
      "HWP v5 pagination is approximated when the binary producer omits usable page geometry"
    ],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "typst",
    "label": "Typst",
    "category": "document",
    "extensions": [
      "typ",
      "typst"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-typst",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "Typst source"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": "adapter",
      "exportHtml": "adapter",
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "archive",
    "label": "Archive",
    "category": "archive",
    "extensions": [
      "zip",
      "zipx",
      "7z",
      "rar",
      "tar",
      "gz",
      "gzip",
      "tgz",
      "bz2",
      "bzip2",
      "tbz",
      "tbz2",
      "xz",
      "txz",
      "lzma",
      "zst",
      "tzst",
      "cab",
      "ar",
      "cpio",
      "iso",
      "xar",
      "lha",
      "lzh",
      "jar",
      "war",
      "ear",
      "apk",
      "cbz",
      "cbr"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-archive",
    "presets": [
      "standard",
      "all"
    ],
    "containerVersions": [
      "libarchive-supported containers"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "email",
    "label": "Email",
    "category": "email",
    "extensions": [
      "eml",
      "msg",
      "mbox"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-email",
    "presets": [
      "standard",
      "all"
    ],
    "containerVersions": [
      "MIME",
      "Outlook MSG",
      "mbox"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "eda",
    "label": "EDA",
    "category": "eda",
    "extensions": [
      "olb",
      "dra",
      "gds",
      "oas",
      "oasis"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-eda",
    "presets": [
      "engineering",
      "all"
    ],
    "containerVersions": [
      "OrCAD",
      "GDSII",
      "OASIS"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "cad",
    "label": "CAD",
    "category": "cad",
    "extensions": [
      "dxf",
      "dwg",
      "dwf",
      "dwfx",
      "xps"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-cad",
    "presets": [
      "engineering",
      "all"
    ],
    "containerVersions": [
      "DWG",
      "DXF",
      "DWF",
      "DWFX/XPS"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": false
    }
  },
  {
    "id": "model",
    "label": "3D Model",
    "category": "model",
    "extensions": [
      "glb",
      "gltf",
      "obj",
      "stl",
      "ply",
      "fbx",
      "dae",
      "3ds",
      "3mf",
      "amf",
      "usd",
      "usda",
      "usdc",
      "usdz",
      "kmz",
      "step",
      "stp",
      "iges",
      "igs",
      "ifc",
      "3dm",
      "brep",
      "pcd",
      "wrl",
      "vrml",
      "xyz",
      "vtk",
      "vtp"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-3d",
    "presets": [
      "engineering",
      "all"
    ],
    "containerVersions": [
      "Mesh",
      "CAD exchange",
      "scene"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": "provider",
      "search": false
    }
  },
  {
    "id": "geo",
    "label": "Geospatial",
    "category": "geo",
    "extensions": [
      "geojson",
      "kml",
      "gpx",
      "shp"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-geo",
    "presets": [
      "engineering",
      "all"
    ],
    "containerVersions": [
      "GeoJSON",
      "KML",
      "GPX",
      "Shapefile"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "drawing",
    "label": "Drawing",
    "category": "drawing",
    "extensions": [
      "excalidraw",
      "drawio",
      "dio",
      "mermaid",
      "mmd",
      "plantuml",
      "puml"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-drawing",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "Draw.io",
      "Excalidraw",
      "Mermaid",
      "PlantUML"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "mindmap",
    "label": "Mind Map",
    "category": "mindmap",
    "extensions": [
      "xmind"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-mindmap",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "XMind"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "epub",
    "label": "EPUB",
    "category": "ebook",
    "extensions": [
      "epub"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-epub",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "EPUB 2",
      "EPUB 3"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": true,
      "zoom": false,
      "search": "provider"
    }
  },
  {
    "id": "ebook-fb2",
    "label": "FictionBook",
    "category": "ebook",
    "extensions": [
      "fb2"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-epub",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "FictionBook 2 XML"
    ],
    "knownLimits": [
      "External network resources are not loaded"
    ],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "umd",
    "label": "UMD",
    "category": "ebook",
    "extensions": [
      "umd"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-epub",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "UMD"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": true
    }
  },
  {
    "id": "image",
    "label": "Image",
    "category": "image",
    "extensions": [
      "gif",
      "jpg",
      "jpeg",
      "bmp",
      "tiff",
      "tif",
      "png",
      "svg",
      "webp",
      "avif",
      "ico",
      "heic",
      "heif",
      "jxl"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-image",
    "presets": [
      "lite",
      "standard",
      "all"
    ],
    "containerVersions": [
      "Raster",
      "SVG"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": "provider",
      "search": false
    }
  },
  {
    "id": "dicom",
    "label": "DICOM",
    "category": "medical-image",
    "extensions": [
      "dcm",
      "dicom"
    ],
    "async": true,
    "supportLevel": "basic",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-dicom",
    "presets": [],
    "containerVersions": [
      "DICOM Part 10"
    ],
    "knownLimits": [
      "Local single-file and multi-frame viewing only; series assembly, PACS/DICOMweb, MPR, segmentation, measurement tools, and diagnostic-use claims are not included",
      "Tested transfer syntaxes are Implicit/Explicit VR Little Endian, JPEG Lossless Process 14 SV1, JPEG-LS Lossless, and JPEG 2000 Lossless"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": "provider",
      "search": false
    }
  },
  {
    "id": "signature",
    "label": "Digital signatures and evidence containers",
    "category": "cryptographic-container",
    "extensions": [
      "p7m",
      "p7s",
      "p7c",
      "p7b",
      "pkcs7",
      "cms",
      "cmsc",
      "tsd",
      "tst",
      "tsq",
      "tsr",
      "asics",
      "scs",
      "asice",
      "sce",
      "ers",
      "asc",
      "sig",
      "pgp",
      "gpg",
      "jws"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "experimental",
    "packageName": "@file-viewer/renderer-signature",
    "presets": [],
    "containerVersions": [
      "CMS/PKCS#7",
      "CAdES attributes",
      "RFC 3161",
      "RFC 5544",
      "ASiC-S/E",
      "RFC 4998",
      "RFC 7515",
      "OpenPGP RFC 9580"
    ],
    "knownLimits": [
      "Opt-in renderer; it is not added to the published preset-all/full compatibility closure",
      "Cryptographic checks are reported separately from certificate/key trust, policy, qualified-signature status and legal validity",
      "ASiC XML references and RFC 4998 renewal chains are structurally inspected; full XAdES and archival-policy validation are not claimed",
      "OpenPGP private-key operations and automatic decryption are intentionally excluded"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": false
    }
  },
  {
    "id": "markdown",
    "label": "Markdown",
    "category": "markdown",
    "extensions": [
      "md",
      "markdown"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-text",
    "presets": [
      "lite",
      "standard",
      "all"
    ],
    "containerVersions": [
      "CommonMark/GFM"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "code",
    "label": "Code and Text",
    "category": "code",
    "extensions": [
      "txt",
      "json",
      "js",
      "mjs",
      "cjs",
      "css",
      "java",
      "py",
      "html",
      "htm",
      "jsx",
      "ts",
      "tsx",
      "xml",
      "log",
      "vue",
      "yaml",
      "yml",
      "ini",
      "sh",
      "bash",
      "sql",
      "go",
      "rs",
      "php",
      "c",
      "cpp",
      "cc",
      "h",
      "hpp",
      "cs",
      "diff",
      "patch",
      "bundle",
      "bdl",
      "jsonc",
      "json5",
      "ipynb",
      "toml",
      "proto",
      "hcl",
      "tex",
      "gv",
      "http",
      "react",
      "rb",
      "swift",
      "kt"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-text",
    "presets": [
      "lite",
      "standard",
      "all"
    ],
    "containerVersions": [
      "Plain text",
      "source code",
      "Git bundle"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": true,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  },
  {
    "id": "video",
    "label": "Video",
    "category": "media",
    "extensions": [
      "mp4",
      "webm",
      "m3u8"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-media",
    "presets": [
      "lite",
      "standard",
      "all"
    ],
    "containerVersions": [
      "Browser media"
    ],
    "knownLimits": [
      "Codec support follows the browser"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": false
    }
  },
  {
    "id": "audio",
    "label": "Audio",
    "category": "media",
    "extensions": [
      "mp3",
      "mpeg",
      "wav",
      "ogg",
      "oga",
      "opus",
      "m4a",
      "aac",
      "flac",
      "weba",
      "midi",
      "mid"
    ],
    "async": true,
    "supportLevel": "high-fidelity",
    "status": "stable",
    "packageName": "@file-viewer/renderer-media",
    "presets": [
      "lite",
      "standard",
      "all"
    ],
    "containerVersions": [
      "Browser media",
      "MIDI"
    ],
    "knownLimits": [
      "Codec support follows the browser"
    ],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": false,
      "zoom": false,
      "search": false
    }
  },
  {
    "id": "data-asset",
    "label": "Data Asset",
    "category": "asset",
    "extensions": [
      "ttf",
      "otf",
      "woff",
      "woff2",
      "psd",
      "ai",
      "eps",
      "sqlite",
      "wasm",
      "parquet",
      "avro",
      "webarchive"
    ],
    "async": true,
    "supportLevel": "structured",
    "status": "stable",
    "packageName": "@file-viewer/renderer-data",
    "presets": [
      "all"
    ],
    "containerVersions": [
      "Font",
      "design",
      "database",
      "binary data"
    ],
    "knownLimits": [],
    "capabilities": {
      "download": true,
      "print": false,
      "exportHtml": true,
      "zoom": false,
      "search": true
    }
  }
] as const satisfies readonly RendererDefinition[];

export const DEFAULT_REGISTERED_EXTENSIONS = Object.freeze(
  Array.from(new Set(DEFAULT_RENDERER_DEFINITIONS.flatMap(definition => definition.extensions))).sort()
);

export const DEFAULT_STABLE_SUPPORTED_EXTENSIONS = Object.freeze(
  Array.from(new Set(DEFAULT_RENDERER_DEFINITIONS
    .filter(definition => definition.status === 'stable')
    .flatMap(definition => definition.extensions))).sort()
);

/** @deprecated Use DEFAULT_REGISTERED_EXTENSIONS when the experimental/stable distinction matters. */
export const DEFAULT_SUPPORTED_EXTENSIONS = DEFAULT_REGISTERED_EXTENSIONS;
